# -*- coding: utf-8 -*-
"""Data cleansing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uf2shM-Lk1P0WfHgHxX3koXfW7L4CsuY
"""

import pandas as pd
import numpy as np

movies_data=pd.read_csv('/content/movies.csv')
movies_data

movies_data.info()

movies_data.describe()

movies_data=movies_data.rename(columns=({'Gross':'Gross in Millions $'}))

movies_data.drop_duplicates()

"""Movies column cleaning

"""

movies_data['MOVIES']=movies_data['MOVIES'].str.strip()

"""Votes column cleaning

"""

movies_data.isnull().sum()

movies_data['VOTES']=movies_data['VOTES'].fillna('0')

movies_data['VOTES']=movies_data['VOTES'].str.replace(',','')

movies_data['VOTES']=movies_data['VOTES'].astype(int)

movies_data

movies_data.info()

"""Rating

"""

movies_data['RATING']=movies_data['RATING'].fillna(0.0)

movies_data

"""cleaning genre


"""

movies_data['GENRE']=movies_data['GENRE'].str.strip('\n')

movies_data

movies_data[['Type1','Type2','Type3']]=movies_data['GENRE'].str.split(',',2,expand=True)

movies_data

movies_data.drop(columns='GENRE')

"""Rename the One-line column

"""

movies_data=movies_data.rename(columns=({'ONE-LINE':'DESCRIPTION'}))

movies_data['DESCRIPTION']=movies_data['DESCRIPTION'].str.strip('\n')

movies_data

"""Cleaning the YEAR column

"""

movies_data['YEAR']=movies_data['YEAR'].str.replace('(','')

movies_data['YEAR']=movies_data['YEAR'].str.replace(')','')

movies_data['YEAR']=movies_data['YEAR'].str.strip()

movies_data['YEAR']=movies_data['YEAR'].str.strip('–')

movies_data

"""Splitting the STAR column

"""

movies_data['STARS']=movies_data['STARS'].str.strip('\n')

movies_data['STARS']=movies_data['STARS'].str.replace('\n','')

movies_data['STARS']=movies_data['STARS'].str.strip()

movies_data['STARS']=movies_data['STARS'].str.replace('Star','Stars')

movies_data['STARS']=movies_data['STARS'].str.replace('Starss','Stars')

movies_data[['DIRECTOR','ACTORS']]=movies_data['STARS'].str.split('Stars:',1,expand=True)

movies_data['DIRECTOR']=movies_data['DIRECTOR'].str.replace('Director:','')

movies_data['DIRECTOR']=movies_data['DIRECTOR'].str.replace('|','')

movies_data=movies_data.drop(columns='STARS')

movies_data=movies_data.drop(columns='GENRE')

movies_data

"""RUN TIME Column

"""

movies_data['RunTime']=movies_data['RunTime'].fillna(0.0)

movies_data

"""Gross in $ column cleaning"""

movies_data['Gross in Millions $']=movies_data['Gross in Millions $'].fillna('0$')

movies_data

movies_data=movies_data.drop_duplicates()

movies_data

movies_data.to_excel('Cleaned_dataset.xlsx',index=False)

